CREATE SCHEMA HR;

CREATE SEQUENCE HR.NWU_GENERIC_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE HR.ACCOUNT_TYPE (
  ACCOUNT_TYPE_ID number(15) not null,
  MNEMONIC varchar(50) not null,
  ACCOUNT_TYPE_NAME varchar(50) not null,
  CREATION_DATE date,
    CONSTRAINT PK_ACCOUNT_TYPE_ID PRIMARY KEY (ACCOUNT_TYPE_ID)
);


CREATE TABLE HR.ACCOUNT_TRANSAX (
  ACCOUNT_TRANSAX_ID number(15) not null,
  ACCOUNT_TYPE_ID number(15) not null,
  MEMBER_ID number(15) not null,
  AMOUNT number(6) not null,
  TRANSAX_DATE date not null,
    CONSTRAINT PK_ACCOUNT_TRANSAX_ID PRIMARY KEY (ACCOUNT_TRANSAX_ID),
    CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID)
     REFERENCES ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
);
